### ISSUE TITLE
does not work on RTL Arabic Language

### ISSUE THREAD

**Issue by huzaifaTkd** [animate-react-native/marquee#6]
Updated language switch to RTL mode; addressed library limitations and corrected default behavior to align with RTL settings.

**Comment by catalinmiron** [comment]
Since `0.3.0` I have added support for `reverse` and you can add `reverse={I18nManager.isRTL}`

Feel free to re-open the issue if this is not working. Thanks!

**Comment by KhawajaKing** [comment]
Some how its not working for me  like below.
reverse={I18nManager.isRTL}

**Comment by KhawajaKing** [comment]
<img width="659" alt="image" src="https://github.com/user-attachments/assets/2292e989-61d6-4cb8-a422-1a2c9a6e99e4">

**this works for me, if i pass directly like above image then its working**
